import{S as b,a as y,i as u}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function L({largeImageURL:o,webformatURL:r,tags:s,likes:i,views:e,comments:t,downloads:n}){return`<li class="gallery-item">
   <a class="gallery-link" href="${o}">
   <img class="gallery-image"
   src="${r}" 
   alt="${s}" />
  </a> <div class="info-box">
  <p>Likes:<span> ${i}</span></p>
        <p>Views:<span> ${e}</span></p>
        <p>Comments:<span> ${t}</span></p>
        <p>Downloads:<span> ${n}</span> </p>    
    </div>
  </li>`}let F=new b(".gallery a",{captionDelay:250,captionsData:"alt",captionPosition:"bottom"});function f(o){const r=o.map(L).join("");a.gallery.insertAdjacentHTML("beforeend",r),F.refresh()}const m=15;async function p(){return y.defaults.baseURL="https://pixabay.com/api/",(await y.get("",{params:{key:"42132229-e88b92984f0d2a7001cb07c65",image_type:"photo",orientation:"horizontal",safesearch:"true",q:g,page:c,per_page:m}})).data}const a={formEl:document.querySelector(".form"),inputEl:document.querySelector(".query"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoad:document.querySelector(".load-more")};let g="",c=1,d=0;a.formEl.addEventListener("submit",q);a.btnLoad.addEventListener("click",w);function l(){a.loader.classList.toggle("hidden")}async function q(o){o.preventDefault(),l();let r=o.target.elements.query.value;if(g=r,r.trim()==="")u.show({message:"Please full the input field",messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight"});else try{a.gallery.innerHTML="",a.btnLoad.style.display="none",c=1;const s=await p();h(),s.hits.length>0?(f(s.hits),a.btnLoad.style.display="block"):(a.gallery.innerHTML="",a.btnLoad.style.display="none",u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight"}))}catch(s){console.error("Error data:",s)}l(),o.target.reset()}async function w(){l(),h(),c+=1;const o=await p();f(o.hits),l()}async function h(){d=(await p()).totalHits,d!==void 0&&d<=c*m&&(a.btnLoad.style.display="none",u.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight"}))}
//# sourceMappingURL=commonHelpers.js.map
